export const ADMIN_DELETE_REQUEST = "ADMIN_DELETE_REQUEST";
export const ADMIN_DELETE_SUCCESS = "ADMIN_DELETE_SUCCESS";
export const ADMIN_DELETE_ERROR = "ADMIN_DELETE_ERROR";
export const ADMIN_DELETE_ID = "ADMIN_DELETE_ID";
