export const USER_CHANGE_STATUS_REQUEST = "USER_CHANGE_STATUS_REQUEST";
export const USER_CHANGE_STATUS_SUCCESS = "USER_CHANGE_STATUS_SUCCESS";
export const USER_CHANGE_STATUS_ERROR = "USER_CHANGE_STATUS_ERROR";
