version: '3'
services:
  symfony.nginx:
    image: dobriux/docker:symfony.nginx
    ports:
      - "8080:80"
    volumes:
      - ./../:/code
    networks:
      - default

  symfony.php:
    image: dobriux/docker:php7.3
    volumes:
      - ./../:/code
    networks:
      - default

  symfony.mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: qAEcE5des7L4tm3n
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: 68V3wwuCQUUC67Kh
    networks:
      - default

  symfony.node:
    image: dobriux/docker:node
    volumes:
      - ./../:/code
    networks:
      - default
